/* A program that reads in a file and stores the data according to a key
generated by a hash function in a table. If the key produced by the data produces
a similar key to the one previously generated, it will stored the data in the same
key but i will link the data to that key. Eventually, by the end, data will be
stored in a position by a given key. If collision occurs, then it will prduce
linked-lists. Then, the program will open an SDL window where instructions will be
rendered; followed by a display of 4x4 pixels detailing the ammount of linked-lists
each location has in the table. This helps to visualize hotspots within the table,
and possible how the hash function could be further improved To render text onto
the SDL window, a font file is provided within the directory.*/

#include "dhash.h"

int main(int argc, char **argv){

  Data *tableptr = NULL;

  tableptr = initTable(tableptr, PRIME);
  tableptr = readFile(argc, argv, tableptr, PRIME);

  free(tableptr);
  return 0;
}

Data *readFile(int argc, char **argv, Data *tableptr, int prime){

  FILE *fp;
  char names[WORDSIZE];
  int cnt = 0, array_size;

  if( argc >= 2 ){
    if((fp = fopen(argv[1], "r")) == NULL){
      printf("ERROR: Incorrect usage, try e.g. %s eowl_shuffle.txt\n", argv[0]);
      exit (EXIT_FAILURE);
    }
    else{
      while(fscanf(fp, "%s", names) == 1){
        /* keeps track of how many words' been read and it inserts data
        while the table is not full*/
        cnt++;
        if(!(tableFull(cnt, prime))){
          insertData(tableptr, names, prime);
        }
        else{ /*double the table if previous table is close to full*/
          insertData(tableptr, names, prime);
          array_size = prime;
          prime = doublePrime(prime);
          tableptr = crateNewTable(tableptr, prime, array_size);
        }
      }
    }
    fclose(fp);
  }

  openSDLInstructions();
  openSDL(tableptr, prime);
  return tableptr;
}
